413 changehandle
ProjectLibertyLabs/gateway pull request #458
Opened 2024-08-29 17:24 UTC by claireolmstead

# Problem

We do not have an endpoint to return an encoded payload for signing a change handle call.

Link to GitHub Issue(s): #413 

# Solution

- Create GET endpoint to return an encoded payload.
- Remove encoding from the POST change handle.

with @JoeCap08055 @enddynayn 

## Steps to Verify:

1. Get encoded extrinsic
2. Post change handle

2024-08-29 17:26 UTC, claireolmstead commented on services/account/apps/api/src/metadata.ts
> -            WalletLoginResponse: {
I didn't change any of this code. was the metadata just out of date?

2024-08-29 17:28 UTC, JoeCap08055 commented on services/account/apps/api/src/controllers/v1/handles-v1.controller.ts
> +  @ApiOkResponse({ description: 'ClaimHandlePayload request enqueued' })
```suggestion
  @ApiOkResponse({ description: 'Returned an encoded ClaimHandlePayload for signing' })
```

2024-08-29 17:45 UTC, JoeCap08055 commented on services/account/apps/api/src/services/handles.service.ts
> +  async encodePayload(payload: HandleRequest['payload']): Promise<CommonPrimitivesHandlesClaimHandlePayload> {
```suggestion
 encodePayload(payload: HandleRequest['payload']): CommonPrimitivesHandlesClaimHandlePayload {
```

2024-08-29 17:46 UTC, JoeCap08055 commented on services/account/apps/api/src/controllers/v1/handles-v1.controller.ts
> +      const encodedPayload = await this.handlesService.encodePayload(payload);
So, this gives us a SCALE-encoded payload. But we need to sign raw bytes. So what we actually need to return is a Byte-wrapped array of bytes, encoded as a hex string. Like so:
```suggestion
      const encodedPayload = u8aToHex(u8aWrapBytes(this.handlesService.encodePayload(payload).toU8a()));
```

Also, `encodePayload` shouldn't be `async`, so we don't need `await`.

2024-08-29 18:10 UTC, JoeCap08055 requested changes

2024-08-29 18:10 UTC, JoeCap08055 commented on services/account/apps/api/src/services/handles.service.ts
> +    return lastFinalizedBlockNumber + 10;
FYI the standard expiration we adopted in SIWF for claiming a handle is 10 minutes (= 600 / SECONDS_PER_BLOCK) blocks.

Though I wonder if (time in seconds) should be an (optional) input parameter to the `GET` endpoint; if not provided we could assume 10 minutes. I think we should add that; it's easy enough. If there are no objections @mattheworris @claireolmstead , I'll add it to the issue AC.

2024-08-29 18:10 UTC, JoeCap08055 commented on services/account/libs/common/src/types/dtos/handles.request.dto.ts
> +  @IsNotEmpty()
FYI I don't think these `class-validator` decorators have any effect on return types; only on input types.

2024-08-29 18:10 UTC, JoeCap08055 commented on services/account/swagger.json
Don't forget to re-generate this file again after making more changes to the controller.

2024-08-30 18:47 UTC, JoeCap08055 approved these changes

2024-08-30 20:42 UTC, mattheworris commented on services/account/apps/api/src/services/handles.service.ts
> +    return lastFinalizedBlockNumber + 10;
10 blocks may not be long enough to enable signing of this transaction

100@ 6 seconds or 50 @ 12 seconds should probably be a default constant from the config service
```suggestion
    return lastFinalizedBlockNumber + 100;
```
or if we add `@Query('expirationTime') expirationTime?: number,` to the endpoint.
```suggestion
    return lastFinalizedBlockNumber + expirationTime/SECS_PER_BLOCK; //Pseudocode
```

2024-08-30 20:45 UTC, mattheworris requested changes
- Read through changes
- Requesting updates to block expiration

2024-09-03 18:56 UTC, mattheworris approved these changes

2024-09-03 19:13 UTC, merged